Repository awslabs/amazon-kinesis-client, pull requests merged in 2018-08, with the labels that each got.

#356 Fix for failing testExceptionInProcessingStopsRequests
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/ShardConsumerTest.java
Labels: bug, v2.x

#371 Use AFTER_SEQUENCE_NUMBER when reconnecting
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/IteratorBuilder.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisher.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/IteratorBuilderTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisherTest.java
Labels: v2.x

#372 Upgrade to AWS SDK 2.0.1
  amazon-kinesis-client/pom.xml
Labels: v2.x

#373 Update the lastRequestTime to prevent overlapping restarts.
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumer.java
Labels: v2.x

#377 Advance version and release notes for 2.0.1
  CHANGELOG.md
  README.md
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  pom.xml
Labels: v2.x

#378 Updates release notes for PR #368
  CHANGELOG.md
  README.md
Labels: v2.x

#379 Updating README and version information
  README.md
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  pom.xml
Labels: v2.x

#383 Respect logWarningForTaskAfterMillis for logging a retrieval warning
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumer.java
Labels: v2.x

#376 Feature/v1.x/proxy support
  src/main/java/com/amazonaws/services/kinesis/multilang/MultiLangDaemonConfig.java
  src/test/java/com/amazonaws/services/kinesis/multilang/MultiLangDaemonConfigTest.java
Labels: v1.x

#385 Cleaning up configuration
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/CoordinatorConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/CoordinatorFactory.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/SchedulerCoordinatorFactory.java
Labels: v2.x

#386 Upgrading KCL to use commons-lang 3.7
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/coordinator/KinesisClientLibConfiguration.java
  amazon-kinesis-client-multilang/src/test/java/com/amazonaws/services/kinesis/multilang/config/KinesisClientLibConfiguratorTest.java
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/ConfigsBuilder.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/KinesisShardDetector.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/ShardInfo.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/ShardSyncer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRenewer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/metrics/MetricsUtil.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/AggregatorUtil.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutConsumerRegistration.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcher.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/PrefetchRecordsPublisher.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/ShardSyncerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutConsumerRegistrationTest.java
Labels: v2.x

#387 Fixed typo in terminate log message
  amazon-kinesis-client-multilang/src/main/java/com/amazonaws/services/kinesis/multilang/MultiLangDaemon.java
Labels: v2.x

#388 Change the CoordinatorFactory deprecated methods to default
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/CoordinatorFactory.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/SchedulerCoordinatorFactory.java
Labels: v2.x

#389 Changed to use standard release process for the 1.x versions
  pom.xml
Labels: v1.x

#369 Introduce initialization exception handler in KCL V2
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/WorkerStateChangeListener.java
Labels: v2.x
