Repository awslabs/amazon-kinesis-client, pull requests merged in 2023-02, with the labels that each got.

#1028 Refactored `MultiStreamTracker` to provide and enhance OOP for both
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/ConfigsBuilder.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/DeprecationUtils.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/MultiStreamTracker.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/SingleStreamTracker.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/StreamTracker.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/ConfigsBuilderTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/DeprecationUtilsTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/processor/SingleStreamTrackerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/RetrievalConfigTest.java
Labels: v2.x

#1040 Increased logging verbosity around lease management
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/PeriodicShardSyncManager.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/HierarchicalShardSyncer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseCleanupManager.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRefresher.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRenewer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseTaker.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShutdownTask.java
Labels: v2.x

#1034 Optimization: 9~15% improvement in `KinesisDataFetcher` wall-time after
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/KinesisShardDetector.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/AWSExceptionManager.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcher.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcherTest.java
Labels: v2.x

#1035 Release Note updates to avoid duplication and bitrot (e.g., 1.x release
  CHANGELOG.md
  README.md
Labels: v2.x

#1042 Updated the dependency to fix vulnerability issue
  CHANGELOG.md
  pom.xml
  src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.java
Labels: v1.x, dependencies

#1045 Fixed duplication of project version in children pom.xml
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  pom.xml
Labels: v2.x

#1049 Add release notes 1.14.10 in README.md
  README.md
Labels: v1.x
