Repository awslabs/amazon-kinesis-client, pull requests merged in 2023-08, with the labels that each got.

#1152 Adding resharding integration tests and changing ITs to not run by default
  README.md
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/application/TestConsumer.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/application/TestRecordProcessor.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/application/TestRecordProcessorFactory.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/KCLAppConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/ReleaseCanaryStreamingReshardingTestConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/BasicStreamConsumerIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/ReshardIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/ReshardOptions.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/StreamExistenceManager.java
Labels: v2.x

#1184 [#367] Enhanced multi-lang `AWSCredentialsProvider=...` decoder and c…
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/MultiLangDaemonConfig.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/MultiLangShardRecordProcessor.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/NestedPropertyKey.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/NestedPropertyProcessor.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/auth/KclSTSAssumeRoleSessionCredentialsProvider.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/AWSCredentialsProviderPropertyValueDecoder.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/BuilderDynaBean.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/KinesisClientLibConfigurator.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MultiLangDaemonConfigTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/NestedPropertyKeyTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/auth/KclSTSAssumeRoleSessionCredentialsProviderTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/config/AWSCredentialsProviderPropertyValueDecoderTest.java
  amazon-kinesis-client-multilang/src/test/resources/multilang.properties
Labels: enhancement, v2.x

#1186 Provided documentation for multilang's new NestedPropertyKey enhancem…
  docs/multilang/configuring-credential-providers.md
Labels: multi lang daemon, v2.x

#1187 Release of 2.5.2
  CHANGELOG.md
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  pom.xml
Labels: v2.x

#1188 Reintroduced `-SNAPSHOT` classifier on KCL version.
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  pom.xml
Labels: v2.x

#1200 add test case for StreamIdentifier serialization
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamIdentifierTest.java
Labels: v2.x

#1202 Initial FAQ, with hopefully more contributions in the future.
  docs/FAQ.md
Labels: v2.x

#1203 Added links from `README.md` to FAQ and doc folder.
  README.md
Labels: v2.x
