Repository awslabs/amazon-kinesis-client, pull requests merged in 2023-04, with the labels that each got.

#1089 Bump awssdk.version from 2.20.8 to 2.20.40
  pom.xml
Labels: v2.x, dependencies

#1088 Minimize race in PSSM to avoid unnecessary shard sync calls
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/PeriodicShardSyncManager.java
Labels: v2.x

#1094 Code cleanup to introduce better testing and simplify future removal of
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/ProcessorConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalSpecificConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/PollingConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/ConfigsBuilderTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamConfigTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/ShardConsumerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/RetrievalConfigTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutConfigTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/polling/PollingConfigTest.java
Labels: v2.x

#1096 Added `SupplierCache` (so it may be leveraged by StreamARN work).
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/SupplierCache.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/SupplierCacheTest.java
Labels: v2.x

#1087 Internally construct StreamARN using STS
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/ConfigsBuilder.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamARNUtil.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamIdentifier.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/KinesisShardDetector.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/SingleStreamTracker.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcher.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/ConfigsBuilderTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamARNUtilTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamIdentifierTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/SchedulerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/RetrievalConfigTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/MockObjectHelper.java
  pom.xml
Labels: v2.x

#1097 StreamARN: fast-follow to invent-and-simplify https://github.com/awsl…
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamARNUtil.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamARNUtilTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamIdentifierTest.java
Labels: v2.x

#1098 StreamARN: enhanced `StreamIdentifier` to spawn instances from stream…
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamIdentifier.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/KinesisClientFacade.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamIdentifierTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/PeriodicShardSyncManagerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/SchedulerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/HierarchicalShardSyncerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/KinesisClientFacadeTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutConfigTest.java
Labels: enhancement, v2.x

#1099 StreamARN: removed region from `StreamIdentifier` serialization.
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamARNUtil.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamIdentifier.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamARNUtilTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamIdentifierTest.java
Labels: v2.x
