Repository awslabs/amazon-kinesis-client, pull requests merged in 2023-06, with the labels that each got.

#1108 Add support for Stream ARNs
  src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfiguration.java
  src/main/java/com/amazonaws/services/kinesis/clientlibrary/proxies/KinesisProxy.java
  src/test/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibConfigurationTest.java
  src/test/java/com/amazonaws/services/kinesis/clientlibrary/proxies/KinesisProxyTest.java
Labels: enhancement, v1.x

#1145 GitHub actions
  .github/workflows/maven.yml
Labels: v1.x, v2.x

#1146 Adding github actions workflow for 1.x
  .github/workflows/maven.yml
Labels: v1.x

#1136 Adding testing architecture and KCL 2.x basic polling/streaming tests
  README.md
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/KCLAppConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/ReleaseCanaryPollingH1TestConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/ReleaseCanaryPollingH2TestConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/ReleaseCanaryStreamingTestConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/BasicStreamConsumerIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/AWSResourceManager.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/LeaseTableManager.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/RecordValidationStatus.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/RecordValidatorQueue.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/RecordValidatorQueueTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/ReshardOptions.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/StreamExistenceManager.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/TestConsumer.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/TestRecordProcessor.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/TestRecordProcessorFactory.java
Labels: v2.x

#1148 Code cleanup to faciliate Checkstyle enforcement.
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/checkpoint/ShardRecordProcessorCheckpointer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/checkpoint/dynamodb/DynamoDBCheckpointer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/HashKeyRangeForLease.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/NoOpWorkerStateChangeListener.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/PeriodicShardSyncManager.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/Scheduler.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/coordinator/WorkerStateChangeListener.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/HierarchicalShardSyncer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseCleanupManager.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseManagementConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/ShardSyncTask.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRefresher.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseSerializer.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/exceptions/CustomerApplicationException.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ProcessTask.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumerSubscriber.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShutdownTask.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/metrics/CloudWatchMetricKey.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/metrics/MetricDatumWithKey.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisher.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutRetrievalFactory.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/PollingConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/PrefetchRecordsPublisher.java
Labels: v2.x

#1149 Bound Checkstyle to `validate` goal for automated enforcement.
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/ShardConsumerSubscriber.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisher.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcher.java
  checkstyle/checkstyle-suppressions.xml
  checkstyle/checkstyle.xml
  pom.xml
Labels: v2.x

#1143 Update to Multilang Daemon to support StreamArn
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/KinesisClientLibConfigurator.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/MultiLangDaemonConfiguration.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MessageReaderTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MessageWriterTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MultiLangDaemonConfigTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MultiLangDaemonTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MultiLangProtocolTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/ReadSTDERRTaskTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/StreamingShardRecordProcessorFactoryTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/config/AWSCredentialsProviderPropertyValueDecoderTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/config/KinesisClientLibConfiguratorTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/messages/MessageTest.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamIdentifier.java
Labels: v2.x

#1150 Enabled Checkstyle validation of test resources.
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MessageReaderTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MessageWriterTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MultiLangDaemonConfigTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/ReadSTDERRTaskTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/StreamingShardRecordProcessorTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/checkpoint/CheckpointerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/checkpoint/InMemoryCheckpointer.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/checkpoint/ShardShardRecordProcessorCheckpointerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/DeterministicShuffleShardSyncLeaderDeciderTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/DiagnosticEventsTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/PeriodicShardSyncManagerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/SchedulerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/WorkerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/HierarchicalShardSyncerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/LeaseCoordinatorExerciser.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/ShardObjectHelper.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRenewerBillingModePayPerRequestIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRenewerIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRenewerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/metrics/MetricAccumulatingQueueTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisherTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcherTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/polling/PrefetchRecordsPublisherIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/polling/PrefetchRecordsPublisherTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/BlockingUtils.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/SubscribeToShardRequestMatcher.java
  checkstyle/checkstyle.xml
  pom.xml
Labels: v2.x

#1153 Checkstyle: added `UnusedImports` check.
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/MultiLangRecordProcessorFactory.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/AWSCredentialsProviderPropertyValueDecoder.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/BuilderDynaBean.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/KinesisClientLibConfigurator.java
  amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/MultiLangDaemonConfiguration.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MessageWriterTest.java
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/MultiLangProtocolTest.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/MultiStreamLease.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/metrics/MetricDatumWithKey.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisher.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/checkpoint/InMemoryCheckpointer.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/config/KCLAppConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/GracefulShutdownCoordinatorTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/WorkerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/LeaseIntegrationBillingModePayPerRequestTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/ShardInfoTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseCoordinatorIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRefresherTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseTakerIntegrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/BlockOnParentShardTaskTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/lifecycle/ShardConsumerSubscriberTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutConsumerRegistrationTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisherTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/AWSResourceManager.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/LeaseTableManager.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/StreamExistenceManager.java
  checkstyle/checkstyle.xml
Labels: v2.x

#1154 Checkstyle: added additional checks to, primarily, safeguard against …
  amazon-kinesis-client-multilang/src/test/java/software/amazon/kinesis/multilang/messages/MessageTest.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/checkpoint/ShardShardRecordProcessorCheckpointerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/metrics/EndingMetricsScopeTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/AWSExceptionManagerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/ThrottlingReporterTest.java
  checkstyle/checkstyle.xml
Labels: v2.x

#1157 Fix NPE on graceful shutdown before DDB `LeaseCoordinator` starts.
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseCoordinator.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseCoordinatorTest.java
Labels: bug, v2.x

#1159 Bug fix in lease refresher integration test with occasional failures
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/leases/dynamodb/DynamoDBLeaseRefresherIntegrationTest.java
Labels: v2.x
