Repository awslabs/amazon-kinesis-client, pull requests merged in 2023-05, with the labels that each got.

#1107 Refactored `SynchronizedCache` out of `SupplierCache`, and introduced
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/FunctionCache.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/SupplierCache.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/SynchronizedCache.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/FunctionCacheTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/SynchronizedCacheTest.java
Labels: v2.x

#1106 Added missing copyright to new files.
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamARNUtil.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/SupplierCache.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/KinesisClientFacade.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamARNUtilTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/SupplierCacheTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/KinesisClientFacadeTest.java
Labels: v2.x

#1111 Backport "Prevent HashRangesAreAlwaysComplete test from building invalid hierarchy trees"
  src/test/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/PeriodicShardSyncManagerTest.java
Labels: v1.x

#1109 Add support for stream ARNs
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/ConfigsBuilder.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/FunctionCache.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamARNUtil.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/StreamIdentifier.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/SupplierCache.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/SynchronizedCache.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/KinesisShardDetector.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/SingleStreamTracker.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/KinesisClientFacade.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/polling/KinesisDataFetcher.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/ConfigsBuilderTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/FunctionCacheTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamARNUtilTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/StreamIdentifierTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/SupplierCacheTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/common/SynchronizedCacheTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/coordinator/SchedulerTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/KinesisClientFacadeTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/retrieval/RetrievalConfigTest.java
  amazon-kinesis-client/src/test/java/software/amazon/kinesis/utils/MockObjectHelper.java
Labels: enhancement, v2.x

#1115 Update KCL version to 2.5.1-SNAPSHOT
  amazon-kinesis-client-multilang/pom.xml
  amazon-kinesis-client/pom.xml
  amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java
  pom.xml
Labels: v2.x
